### PR TITLE
More fixes and enhancements for 2.0.0

### LINKED ISSUE #530: No results are copied to any output directory
After a successful run they are staying in the work/... directory. When using /scratch it means we are loosing the results altogether. Command line was:
```nextflow run /home/szilva/sarek/default/somaticVC.nf -profile singularityPath --tools strelka --genome GRCh38 --genome_base /sw/data/uppnex/ToolBox/hg38bundle --sample Preprocessing/Recalibrated/recalibrated.tsv --containerPath /home/szilva/sarek/containers/ --noReports --verbose```

### LINKED ISSUE #539: Use Nextflow support for /scratch instead of running directly from /scratch
cf https://www.nextflow.io/docs/latest/process.html#scratch

### PR DESCRIPTION
**Pull request by MaxUlysse**
- remove UPPMAX directories from containers
- `--version` is now used to define the version of the workflow
- move `version` to `base.config` within the params `--version`
- update `RELEASE_CHECKLIST.md`
- add `lib/SarekUtils.groovy`
- move `checkParams`, `checkParameterList`, `checkParameterExistence` and `isAllowedParams` functions into `SarekUtils`
- `nfRequiredVersion` is now a `params`
- in `buildReferences.nf` channels now begin by `ch_`, and files by `f_`
- use `PublishDir mode: 'link'` instead of copy
- use `$PWD` for default `outDir` to fix #530 
- `directoryMap` now contains `params.outDir`
- use Nextflow support of scratch to close #539 
- update documentation
- add CHANGELOG

### CODE REVIEW

File: lib/MyUtils.groovy [hunk 1]
```diff
@@ -0,0 +1,93 @@
+class MyUtils {
```
Comment (ewels) [inline lib/MyUtils.groovy]: Nice, very tidy! Maybe better to call `SarekUtils` instead of `MyUtils` though, so that it's clearer in `main.nf`?

File: main.nf [hunk 2]
```diff
@@ -989,22 +877,10 @@ def helpMessage() {
   log.info "       you're reading it"
   log.info "    --verbose"
   log.info "       Adds more verbosity to workflow"
-  log.info "    --version"
+  log.info "    --more"
```
Comment (ewels) [inline main.nf]: This looks wrong?

File: lib/MyUtils.groovy (hunk 1 above)
Comment (MaxUlysse) [reply lib/MyUtils.groovy]: Good idea
